<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Meetings</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

        <script type="application/javascript">
            function uploadAudio() {
                console.log("Uploading a file!");
                var formData = new FormData('uploadAudio');

    //            formData.append("username", "Groucho");
    //            formData.append("accountnum", 123456); // number 123456 is immediately converted to a string "123456"

                // HTML file input, chosen by user
                formData.append("userfile", fileInputElement.files[0]);

                // JavaScript file-like object
    //            var content = '<a id="a"><b id="b">hey!</b></a>'; // the body of the new file...
    //            var blob = new Blob([content], { type: "text/xml"});
    //
    //            formData.append("webmasterfile", blob);

                var request = new XMLHttpRequest();
                request.open("POST", "/meeting");
                request.send(formData);
            }
        </script>

    </head>

    <body style="margin-top: 2em;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <h1>Welcome <strong>Test Subject</strong></h1>
                </div>
                <div class="col" style="text-align: right;">
                    <form name="uploadAudio" enctype="multipart/form-data" action="/meeting" method="POST">
                        <!-- MAX_FILE_SIZE must precede the file input field -->
                        <input type="hidden" name="MAX_FILE_SIZE" value="300000" />
                        <input name="upfile" type="file" />
<!--                        <input type="submit" class="btn btn-primary" value="Upload Audio File" />-->
                        <button onclick="uploadAudio()" class="btn btn-primary" >Upload Audio File"</button>
                    </form>
                </div>
            </div>

            <div class="row" style="margin-top: 1em;">
                <div class="col">
                    <table class="table table-striped">
                        <thead class="thead-inverse">
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th><a href="meeting/1">1</a></th>
                                <td><a href="meeting/1">Test Meeting</a></td>
                                <td>2017-03-16 06:00 PM</td>
                                <td>2017-03-16 07:00 PM</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
<!---->
<!--        <h1>Slim</h1>-->
<!--        <div>a microframework for PHP</div>-->
<!---->
<!--        --><?php //if (isset($name)) : ?>
<!--            <h2>Hello --><?//= htmlspecialchars($name); ?><!--!</h2>-->
<!--        --><?php //else: ?>
<!--            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>-->
<!--        --><?php //endif; ?>
<!--    </body>-->
</html>
